### ISSUE TITLE
README.md?

### ISSUE THREAD

**Issue by astrohart** [madskristensen/RestClientVS#1]
This looks really cool.  Mind doing a README.md with maybe any screenshots?

**Comment by madskristensen** [comment]
Yes, I'll do all that stuff next week

**Comment by astrohart** [comment]
I’d like to invite you by the way, to see my new project that demonstrates OAuth to GitHub from WinForms.  Can I send you the link?

Regards,
 
Brian C. Hart, Ph.D.

**Comment by madskristensen** [comment]
Done
