### ISSUE TITLE
Indicate request activity in the text editor

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [madskristensen/RestClientVS#14]
**Is your feature request related to a problem? Please describe.**
I did not immediately notice that a request was in progress as the green arrow doesn't change.

**Describe the solution you'd like**
When the green arrow/play button is clicked, it should change to (e.g. hourglass) indicate the request is in progress, and change back to an arrow when the request is complete.

**Describe alternatives you've considered**
None - the alternative is already implemented - status bar text - which is good, but not as obvious for me.

**Additional context**
I have created a branch that implements this - and below if a GIF of how it looks in use.
If you like the idea, I can submit a PR and you can tell me all the things I got wrong 😁👍🏼

This GIF shows two requests:
 - the first one will fail as there is nothing listening on the endpoint - the green arrow changes to a green hourglass when it is clicked. The green hourglass is replaced by a red arrow (to indicate the request failed) upon completion.
- the second request is a valid request, so you only briefly see the hourglass and upon completion, the green arrow is back to indicate success.

The hourglass is a bit `meh` and the alignment is wrong, but that can be fixed.

![Show progress in rest client](https://user-images.githubusercontent.com/11338430/152147072-64d41f4a-a67b-4bd3-91a9-65bb03ee572c.gif)

The implementation I went for adds a couple of `bool` status fields to the Request that the Play Button adornment uses to determine the correct icon. When the button is clicked, it resets the status fields to indicate it is active before triggering the `Send Request Command`.

The Send Request Command calls a method on the Request to confirm completion and passes it the result status (based on `IsSuccessStatusCode`)

There is some fragility in the result colouring because the Request will be re-created by an edit - not sure that matters much?

**Comment by madskristensen** [comment]
That looks awesome. What a great idea. I would love a PR

**Comment by SQL-MisterMagoo** [comment]
Just having a git authentication issue - once that is resolved I'll create the PR

**Comment by SQL-MisterMagoo** [comment]
Implemented in PR #15
