### ISSUE TITLE
Unable to install extension for VS 2019 Community

### ISSUE THREAD

**Issue by khtan** [madskristensen/RestClientVS#33]
**Describe the bug**
The Visual Studio 2019 Extension explorer does not find this version of REST Client. Instead it points to AdrianDev's version that does not work after installation. 

**To Reproduce**
So, I downloaded the .vsix from Github and installed directly using the VSIXInstaller.exe in an Admin shell:

>VSIXInstaller.exe /skuName:Community /skuVersion:16.11.18 c:\tmp\RestClientVS.vsix

A dialog appears that "Install failed". It references a log file. Both are attached.

**Expected behavior**
Successful install so that I can use RESTClient from VS 2019 Community instead of using VS Code.

![installFailed](https://user-images.githubusercontent.com/8535034/188523561-5de7328b-d06c-4614-98eb-73afabc7548d.png)
[dd_VSIXInstaller_20220905172010_04f4.log](https://github.com/madskristensen/RestClientVS/files/9492460/dd_VSIXInstaller_20220905172010_04f4.log)

**Comment by madskristensen** [comment]
This is not a bug. I only coded this to work with VS 2022. You can fork the repo and update the references to the VS 2019 SDK and compile it again. That should work. However, it is not something I'm interested in maintaining at this point.
