### ISSUE TITLE
The response is displayed in a new window instead of an output window to format the response

### ISSUE THREAD

**Issue by Varorbc** [madskristensen/RestClientVS#8]
The response is displayed in a new window instead of an output window to format the response

**Comment by madskristensen** [comment]
@Varorbc, what do you mean by "format the response" and why do you think a custom window is better suited for it over the output window?

**Comment by Varorbc** [comment]
For example, if the response content is a very long JSON, it will be very difficult to read in the output window. It will be more appropriate in the custom window, just like the restclient extension experience in vscode.
