### ISSUE TITLE
occlusion problem after folding

### ISSUE THREAD

**Issue by Varorbc** [madskristensen/RestClientVS#9]
### Description
![image](https://user-images.githubusercontent.com/5714438/147807130-008ebc8b-a849-41cf-8797-1ec22e811ced.png)

![image](https://user-images.githubusercontent.com/5714438/147807141-9bb04b9c-b33c-400a-80d8-ae1206fa16f8.png)

**Comment by madskristensen** [comment]
You need to separate the tests by adding a line containing just `###`. 

```
GET https://www.google.com/

###

GET http://bing.com
```

**Comment by Varorbc** [comment]
The issue seems to have been fixed and is no longer recurring
